#!/usr/bin/python3 

from telethon import TelegramClient 
import sys 
import os 
from tqdm.auto import tqdm 
from time import sleep
import argparse
import inquirer
from telethon.sessions import StringSession 
import config 

""" Get api id and hash from https://my.telegram.org """ 

if os.path.exists(config.fullpath):

    config.parser.read(config.fullpath) 
    api_id = config.parser.get('dark-send','api_id') 
    api_hash = config.parser.get('dark-send','api_hash') 
    string = config.parser.get('dark-send','string_session') 

else:
    config.generate_conf() 
    config.parser.read(config.fullpath) 
    api_id = config.parser.get('dark-send','api_id') 
    api_hash = config.parser.get('dark-send','api_hash') 
    string = config.parser.get('dark-send','string_session') 

client = TelegramClient(StringSession(string), api_id, api_hash) 
num = [] 
dif = 0 

def percentage(part,whole): 
    tmp = 100 * float(part)/float(whole)
    return round(tmp,0)

async def display_list(no_chats,chats):

    if not no_chats:
        no_chats = 15

    global client 
    id = {}
    async for dialog in client.iter_dialogs(no_chats):
        id[dialog.name] = dialog.id

    if chats:
        peers = []
        for chat in chats:
            try:
                peers.append(id[chat])
            except:
                pass

        return peers

    dist = []
    for key in id.keys():
        tmp = {}
        tmp['name'] = key
        dist.append(tmp)

    questions = [
    {
    'type': 'checkbox',
    'message': 'Select chat',
    'name': 'Chats',
    'choices': dist,
    'validate': lambda answer: 'Choose atleast one chat' \
            if len(answer) == 0 else True
            }
    ]

    answers = inquirer.prompt(questions,style=inquirer.style)
    peers = []
    for val in answers.values():
        for answer in val:
            peers.append(id[answer]) 

        return peers

def progress(current,total):
      # print('Uploaded', current, 'out of', total,
      #      'bytes: {:.2%}'.format(current / total)) 
      bar_count = percentage(current,total) 
      global num
      global dif
      if not bar_count in num:
          if not num:
              dif = bar_count
              for i in range(int(dif)):
                  pbar.update(1) 
                  # sleep(0.00001) 
              num.append(bar_count)
              if bar_count == 100: 
                  pbar.close() 
                  dif = 0
                  num = []
                  return 
          else:
              for i in range(int(bar_count - dif)):
                  pbar.update(1)
                  # sleep(0.00001)
              dif = bar_count 
              num.append(bar_count)
              if bar_count == 100: 
                  pbar.close() 
                  dif = 0
                  num = []
                  return 
          
async def main(): 

    parser = argparse.ArgumentParser(description='command line telegram client') 
    parser.add_argument('message', type=str,help="the message you would like to send",nargs="*") 
    parser.add_argument('-v','--video',type=str,nargs="+") 
    parser.add_argument('-i','--image',type=str,nargs="+") 
    parser.add_argument('-f','--file',type=str,nargs="+") 
    parser.add_argument('-n','--nchats',type=int,nargs="?",help="no chats to display") 
    parser.add_argument('-c','--chats',type=str,nargs="*",help="name of the chat") 
    parser.add_argument('-a','--album',action="store_true",help="send files as albums") 
    parser.add_argument('-q','--quiet',action="store_true",help="suppress progress bar") 

    args = parser.parse_args() 
    if args.message:
        chats = await display_list(args.nchats,args.chats)  
        for message in args.message: 
            for chat in chats:
                await client.send_message(chat,message)

    elif args.video:
        if not args.album:
            chats = await display_list(args.nchats,args.chats)  
            for video in args.video: 
                for chat in chats:
                    if not args.quiet:
                        global pbar 
                        pbar = tqdm(total=100,desc="Uploading",ncols=85,leave=True,position=0,ascii=True)
                        await client.send_file(chat,video,video=True,progress_callback=progress) 
                        del pbar 
                    else:
                        await client.send_file(chat,video,video=True) 

        else:
            chats = await display_list(args.nchats,args.chats) 
            files_uploaded = []

            for file in args.video:
                if not args.quiet:
                    pbar = tqdm(total=100,desc="Uploading",ncols=85,leave=True,position=0,ascii=True)
                    files_uploaded.append(await client.upload_file(file,progress_callback=progress))
                    del pbar
                else:
                    files_uploaded.append(await client.upload_file(file))

            for chat in chats:
                await client.send_file(chat,files_uploaded,video=True)


    elif args.image:
        if not args.album:
            chats = await display_list(args.nchats,args.chats) 
            for image in args.image:
                for chat in chats:
                    await client.send_file(chat,image,image=True) 
        else:
            chats = await display_list(args.nchats,args.chats) 
            files_uploaded = []

            for file in args.image:
                if not args.quiet:
                    files_uploaded.append(await client.upload_file(file,progress_callback=progress))
                else:
                    files_uploaded.append(await client.upload_file(file))

            for chat in chats:
                await client.send_file(chat,files_uploaded,image=True)


    elif args.file:
        if not args.album:
            chats = await display_list(args.nchats,args.chats) 
            for file in args.file:
                for chat in chats:
                    if not args.quiet:
                        pbar = tqdm(total=100,desc="Uploading",ncols=85,leave=True,position=0,ascii=True)
                        await client.send_file(chat,file,force_document=True,progress_callback=progress) 
                        del pbar
                    else:
                        await client.send_file(chat,file,force_document=True) 

        else: 
            chats = await display_list(args.nchats,args.chats) 
            files_uploaded = []

            for file in args.file:
                if not args.quiet:
                    pbar = tqdm(total=100,desc="Uploading",ncols=85,leave=True,position=0,ascii=True)
                    files_uploaded.append(await client.upload_file(file,progress_callback=progress))
                    del pbar
                else:
                    files_uploaded.append(await client.upload_file(file))

            for chat in chats:
                await client.send_file(chat,files_uploaded,force_document=True)


with client:
    client.loop.run_until_complete(main())
